### ISSUE TITLE
Error: Unable to Get Current Branch Name When Committing with Evergit

### ISSUE THREAD

**Issue by IanSkelskey** [IanSkelskey/evergit#8]
When attempting to commit changes using evergit commit in a local repository, the command fails with the error message:

```log
? Select files to stage:  .gitignore,  README.md,  something.py
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
C:\Users\iansk\AppData\Roaming\nvm\v20.18.0\node_modules\evergit\dist\util\git.js:137
        throw new Error('Unable to get current branch name.');
              ^

Error: Unable to get current branch name.
    at getCurrentBranchName (C:\Users\iansk\AppData\Roaming\nvm\v20.18.0\node_modules\evergit\dist\util\git.js:137:15)
    at C:\Users\iansk\AppData\Roaming\nvm\v20.18.0\node_modules\evergit\dist\cmd\commit.js:41:55
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\iansk\AppData\Roaming\nvm\v20.18.0\node_modules\evergit\dist\cmd\commit.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

**Comment by IanSkelskey** [comment]
This also happened when I cloned an empty repo and tried to use evergit for the first commit.
